CREATE TABLE person(
                         id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name varchar(100) NOT NULL UNIQUE,
                         birth_year int check (birth_year > 1900)
);

CREATE TABLE book(
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      person_id int NOT NULL REFERENCES person(id),
                      name varchar(200) NOT NULL,
                      publish_year int NOT NULL
)